get:
  summary: OpenAPI specification for this API
  description: Gets specification for this API version as an openapi.yaml file.
  operationId: getOpenAPI
  tags:
    - Version
  security: []   # No security
  responses:
    200:
      description: Successfully returned the openapi.yaml file.
      content:
        application/yaml:
          schema: