openapi: 3.0.3

#  This file is part of the eliona project.
#  Copyright © 2022 LEICOM iTEC AG. All Rights Reserved.
#  ______ _ _
# |  ____| (_)
# | |__  | |_  ___  _ __   __ _
# |  __| | | |/ _ \| '_ \ / _` |
# | |____| | | (_) | | | | (_| |
# |______|_|_|\___/|_| |_|\__,_|
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
#  BUT NOT LIMITED  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

info:
  version: 2.1.0
  title: Eliona API
  description: API to access Eliona Smart Building Assistant
  termsOfService: https://www.eliona.io/v2
externalDocs:
  description: Find out more about Eliona
  url: https://www.eliona.io
servers:
  - url: http://api.eliona.io/v2
#security:
#  - apiKey: []

paths:

  /apps/{app-name}:
    $ref: './paths/apps-name.yaml'

  /apps/{app-name}/patches/{patch-name}:
    $ref: './paths/apps-name-patches-name.yaml'

  /assets:
    $ref: './paths/assets.yaml'

  /assets/{asset-id}:
    $ref: './paths/assets-id.yaml'

  /asset-types:
    $ref: './paths/asset-types.yaml'

  /asset-types/{asset-type-name}/attributes:
    $ref: './paths/asset-types-name-attributes.yaml'

  /heaps:
    $ref: './paths/heaps.yaml'

  /widget-types:
    $ref: './paths/widget-types.yaml'

  /dashboards:
    $ref: './paths/dashboards.yaml'

  /dashboards/{dashboard-id}/widgets:
    $ref: './paths/dashboards-id-widgets.yaml'

  /alarm-rules:
    $ref: './paths/alarm-rules.yaml'

  /alarm-rules/{alarm-rule-id}:
    $ref: './paths/alarm-rules-id.yaml'

  /alarms:
    $ref: './paths/alarms.yaml'

  /alarms/{alarm-rule-id}:
    $ref: './paths/alarms-id.yaml'

  /alarms-history:
    $ref: './paths/alarms-history.yaml'

  /alarms-history/{alarm-rule-id}:
    $ref: './paths/alarms-history-id.yaml'

  /alarms-highest:
    $ref: './paths/alarms-highest.yaml'

  /nodes:
    $ref: './paths/nodes.yaml'

  /nodes/{node-ident}:
    $ref: './paths/nodes-ident.yaml'

  /agents:
    $ref: './paths/agents.yaml'

  /agents/{agent-id}:
    $ref: './paths/agents-id.yaml'

  /agents/{agent-id}/devices:
    $ref: './paths/agents-id-devices.yaml'

  /agents/{agent-id}/devices/{agent-device-id}:
    $ref: './paths/agents-id-devices-id.yaml'

  /agents/{agent-id}/devices/{agent-device-id}/mappings:
    $ref: './paths/agents-id-devices-id-mappings.yaml'

  /agents/{agent-id}/devices/{agent-device-id}/mappings/{agent-device-mapping-id}:
    $ref: './paths/agents-id-devices-id-mappings-id.yaml'

tags:
  - name: Nodes
    description: Handle nodes
    externalDocs:
      url: https://www.eliona.io
  - name: Agents
    description: Handle agents
    externalDocs:
      url: https://www.eliona.io
  - name: Alarms
    description: Handle alarms
    externalDocs:
      url: https://www.eliona.io
  - name: Alarm rules
    description: Handle alarm rules
    externalDocs:
      url: https://www.eliona.io
  - name: Apps
    description: Handle apps
    externalDocs:
      url: https://www.eliona.io
  - name: Assets
    description: Handle assets
    externalDocs:
      url: https://www.eliona.io
  - name: Asset types
    description: Handle asset types
    externalDocs:
      url: https://www.eliona.io
  - name: Heaps
    description: Handle Heap data
    externalDocs:
      url: https://www.eliona.io
  - name: Dashboards
    description: Handle dashboards
    externalDocs:
      url: https://www.eliona.io

#components:
#  securitySchemes:
#    apiKey:
#      type: http
#      scheme: bearer
