openapi: 3.0.3

#  This file is part of the eliona project.
#  Copyright © 2022 LEICOM iTEC AG. All Rights Reserved.
#  ______ _ _
# |  ____| (_)
# | |__  | |_  ___  _ __   __ _
# |  __| | | |/ _ \| '_ \ / _` |
# | |____| | | (_) | | | | (_| |
# |______|_|_|\___/|_| |_|\__,_|
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
#  BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

info:
  version: 2.8.6
  title: Eliona REST API
  description:
    The Eliona REST API enables unified access to the resources and data of an Eliona environment.
  contact:
    name: Eliona by IoTEC AG
    url: https://eliona.io
    email: hello@eliona.io
  license:
    name: MIT License
externalDocs:
  description: Find out more about Eliona App SDK
  url: https://github.com/eliona-smart-building-assistant
servers:
  - url: https://{environment}.eliona.io/v2
    variables:
      environment:
        default: name
        description: Environment name to define the server URL
  - url: https://{environment}.eliona.io/api/v2
    variables:
      environment:
        default: name
        description: Environment name to define the server URL
  - url: https://{server}/v2
    variables:
      server:
        default: somewhere:3000
        description: Server of the API
  - url: http://{server}/v2
    variables:
      server:
        default: localhost:3000
        description: Server of the API
security:
  - ApiKeyAuth: []
  - BearerAuth: []

paths:

  /version:
    $ref: './paths/version.yaml'

  /version/openapi.json:
    $ref: './paths/version-openapi.yaml'

  /apps/{app-name}:
    $ref: './paths/apps-name.yaml'

  /apps/{app-name}/patches/{patch-name}:
    $ref: './paths/apps-name-patches-name.yaml'

  /asset-types:
    $ref: './paths/asset-types.yaml'

  /asset-types/{asset-type-name}:
    $ref: './paths/asset-types-name.yaml'

  /asset-types/{asset-type-name}/attributes:
    $ref: './paths/asset-types-name-attributes.yaml'

  # Not yet implemented
  #  /asset-types/{asset-type-name}/attributes/{asset-type-attribute-name}:
  #    $ref: './paths/asset-types-name-attributes-name.yaml'

  /assets:
    $ref: './paths/assets.yaml'

  /assets/{asset-id}:
    $ref: './paths/assets-id.yaml'

  /assets-bulk:
    $ref: './paths/assets-bulk.yaml'

  /assets-bulk/dry-run:
    $ref: './paths/assets-bulk-dry-run.yaml'

  /asset-listener:
    $ref: './paths/asset-listener.yaml'

  /attribute-display:
    $ref: './paths/attribute-display.yaml'

  /data:
    $ref: './paths/data.yaml'

  /data-bulk:
    $ref: './paths/data-bulk.yaml'

  /data-trend/{asset-id}:
    $ref: './paths/data-trend-id.yaml'

  /data-trend-aggregated/{asset-id}:
    $ref: './paths/data-trend-aggregated-id.yaml'

  /data-listener:
    $ref: './paths/data-listener.yaml'

  /data-trends:
    $ref: './paths/data-trends.yaml'

  /data-aggregated:
    $ref: './paths/data-aggregated.yaml'

  /aggregations:
    $ref: './paths/aggregations.yaml'

  /aggregations/{aggregation-id}:
    $ref: './paths/aggregations-id.yaml'

  /widget-types:
    $ref: './paths/widget-types.yaml'

  /widget-types/{widget-type-name}:
    $ref: './paths/widget-types-name.yaml'

  /dashboards:
    $ref: './paths/dashboards.yaml'

  /dashboards/{dashboard-id}:
    $ref: './paths/dashboards-id.yaml'

  /dashboards/{dashboard-id}/widgets:
    $ref: './paths/dashboards-id-widgets.yaml'

  /alarm-rules:
    $ref: './paths/alarm-rules.yaml'

  /alarm-rules/{alarm-rule-id}:
    $ref: './paths/alarm-rules-id.yaml'

  /calculation-rules:
    $ref: './paths/calculation-rules.yaml'

  /calculation-rules/{calculation-rule-id}:
    $ref: './paths/calculation-rules-id.yaml'

  /alarms:
    $ref: './paths/alarms.yaml'

  /alarms/{alarm-rule-id}:
    $ref: './paths/alarms-id.yaml'

  /alarms-history:
    $ref: './paths/alarms-history.yaml'

  /alarms-history/{alarm-rule-id}:
    $ref: './paths/alarms-history-id.yaml'

  /alarms-highest:
    $ref: './paths/alarms-highest.yaml'

  /alarm-listener:
    $ref: './paths/alarm-listener.yaml'

  /nodes:
    $ref: './paths/nodes.yaml'

  /nodes/{node-ident}:
    $ref: './paths/nodes-ident.yaml'

  /agents:
    $ref: './paths/agents.yaml'

  /agents/{agent-class}:
    $ref: './paths/agents-class.yaml'

  /agents/{agent-class}/{agent-id}:
    $ref: './paths/agents-class-id.yaml'

  /agents/{agent-class}/{agent-id}/devices:
    $ref: './paths/agents-class-id-devices.yaml'

  /agent-devices/{agent-class}/{agent-device-id}:
    $ref: './paths/agent-devices-class-id.yaml'

  /agent-devices/{agent-class}/{agent-device-id}/mappings:
    $ref: './paths/agent-devices-class-id-mappings.yaml'

  /agent-device-mappings/{agent-class}/{agent-device-mapping-id}:
    $ref: './paths/agent-device-mappings-class-id.yaml'

  /send-mail:
    $ref: './paths/send-mail.yaml'

  /send-notification:
    $ref: './paths/send-notification.yaml'

  /message-receipts/{message-id}:
    $ref: './paths/message-receipts-id.yaml'

  /qr-codes/assets/{asset-id}:
    $ref: './paths/qr-codes-assets-id.yaml'

  /users:
    $ref: './paths/users.yaml'

  /users/{user-id}:
    $ref: './paths/users-id.yaml'

  /projects:
    $ref: './paths/projects.yaml'

  /projects/{project-id}:
    $ref: './paths/projects-id.yaml'

  /tags:
    $ref: './paths/tags.yaml'

  /tags/{tag-name}:
    $ref: './paths/tags-name.yaml'


tags:
  - name: Nodes
    description: Handle nodes
    externalDocs:
      url: https://www.eliona.io
  - name: Agents
    description: Handle agents
    externalDocs:
      url: https://www.eliona.io
  - name: Alarms
    description: Handle alarms
    externalDocs:
      url: https://www.eliona.io
  - name: Alarm rules
    description: Handle alarm rules
    externalDocs:
      url: https://www.eliona.io
  - name: Apps
    description: Handle apps
    externalDocs:
      url: https://www.eliona.io
  - name: Asset types
    description: Handle asset types
    externalDocs:
      url: https://www.eliona.io
  - name: Assets
    description: Handle assets
    externalDocs:
      url: https://www.eliona.io
  - name: Aggregations
    description: Handle data aggregations
    externalDocs:
      url: https://www.eliona.io
  - name: Data
    description: Handle asset data
    externalDocs:
      url: https://www.eliona.io
  - name: Calculation rules
    description: Handle calculation rules
    externalDocs:
      url: https://www.eliona.io
  - name: Dashboards
    description: Handle dashboards
    externalDocs:
      url: https://www.eliona.io
  - name: Widgets types
    description: Handle widgets types for dashboards
    externalDocs:
      url: https://www.eliona.io
  - name: Widgets
    description: Handle widgets for dashboards
    externalDocs:
      url: https://www.eliona.io
  - name: Communication
    description: Communicate to peoples
    externalDocs:
      url: https://www.eliona.io
  - name: Users
    description: User information
    externalDocs:
      url: https://www.eliona.io
  - name: Projects
    description: Project information
    externalDocs:
      url: https://www.eliona.io
  - name: Tags
    description: Tag information
    externalDocs:
      url: https://www.eliona.io
  - name: QR codes
    description: QR codes for frontend links
    externalDocs:
      url: https://www.eliona.io
  - name: Version
    description: API version
    externalDocs:
      url: https://www.eliona.io

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: Use the API key as a secret for authorizing and identifying an app or agent
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      description: Use the Bearer for authorizing and identifying a frontend access
      scheme: bearer
      bearerFormat: JWT
