### [Data] Get data for asset 4711 filtered by data subtype (read-only)
GET {{api-server}}/v2/data?assetId=4711&dataSubtype=input HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Data] Get data for asset 4711 with multiple filters (read-only)
GET {{api-server}}/v2/data?assetId=4711&parentAssetId=4700&dataSubtype=info HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Data] Create or update asset data with a client reference (read–write)
PUT {{api-server}}/v2/data?directMode=true HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 64609,
  "subtype": "input",
  "data": {
    "Counter": 1234
  },
  "clientReference": "ABC123"
}

### [Data] Get trend of historical data for an asset (data-trend)
GET {{api-server}}/v2/data-trend/64609?dataSubtype=input&attributeName=Counter&fromDate=2025-03-25T13:13:00.000Z&toDate=2025-03-25T14:13:14.000Z&offset=0&size=20 HTTP/1.1
Accept: application/x-ndjson
X-Api-Key: {{read-only-token}}

### [Data] Get aggregated trend of historical data for an asset (data-trend-aggregated)
GET {{api-server}}/v2/data-trend-aggregated/64609?dataSubtype=input&attributeName=Counter&aggregationRaster=1s&sumMethod=sum&fromDate=2025-03-25T13:13:00.000Z&toDate=2025-03-25T14:13:14.000Z&offset=0&size=20 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Data] Put historical data for an asset (data-trend)
PUT {{api-server}}/v2/data-trend HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 64609,
  "subtype": "input",
  "data": {
    "Counter": 680
  },
  "timestamp": "2025-03-25T13:13:14.001Z",
  "clientReference": "ABC123"
}
