### [Nodes] List nodes (read-only)
GET {{api-server}}/v2/nodes HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Nodes] Create a new node with detailed information (read–write)
POST {{api-server}}/v2/nodes HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "id": "fef0a0d3-acad-4611-ac03-1fd842d72505",
  "assetId": 4711,
  "vendor": "VendorName",
  "model": "NodeModelX",
  "siteId": "dec66ddd-7368-4725-8b79-fa20676a9bc8",
  "description": "Edge node for West Plant",
  "enable": true
}

### [Nodes] Get node by id (read-only)
GET {{api-server}}/v2/nodes/01f8c5b3-8047-4876-a161-da0e147406e5 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Nodes] Update node with additional optional fields (read–write)
PUT {{api-server}}/v2/nodes/fef0a0d3-acad-4611-ac03-1fd842d72505 HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "ident": "fef0a0d3-acad-4611-ac03-1fd842d72505",
  "vendor": "VendorName",
  "siteId": "dec66ddd-7368-4725-8b79-fa20676a9bc8",
  "model": "NodeModelX",
  "description": "Updated description for node at West Plant",
  "enable": true
}

### [Nodes] Delete node by id
DELETE {{api-server}}/v2/nodes/01f8c5b3-8047-4876-a161-da0e147406e5 HTTP/1.1
X-Api-Key: {{read-write-token}}