### [Sites] List all sites (read-only)
GET {{api-server}}/v2/sites HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Sites] Stream all sites (read-only)
GET {{api-server}}/v2/sites HTTP/1.1
X-Api-Key: {{read-only-token}}
Accept: application/x-ndjson

### [Sites] Get site by ID (read-only)
GET {{api-server}}/v2/sites/99999999-9999-9999-9999-999999999999 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Sites] Delete site by ID (read-write)
DELETE {{api-server}}/v2/sites/99999999-9999-9999-9999-999999999999 HTTP/1.1
X-Api-Key: {{read-write-token}}

### [Sites] Create a site (read–write)
PUT {{api-server}}/v2/sites HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "name": "Example Site",
  "location": "CH, Winterthur"
}

### [Sites] Create or update a site with id (read–write)
PUT {{api-server}}/v2/sites HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "id": "291aedfd-f600-4eff-86ba-3dd2fecf24be",
  "name": "Example Site",
  "location": "DE, Berlin"
}
