### [Users] List all users (read-only)
GET {{api-server}}/v2/users HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Users] Get a user (read–only)
GET {{api-server}}/v2/users/a5485cd2-3578-45c9-9e0a-62e430ccb3fa HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Users] Delete user by ID (read-write)
DELETE {{api-server}}/v2/users/a5485cd2-3578-45c9-9e0a-62e430ccb3fa HTTP/1.1
X-Api-Key: {{read-write-token}}

### [Users] Create a user (read–write)
PUT {{api-server}}/v2/users HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "email": "foo@bar.de",
  "roleName": "test_role_name"
}