type: object
description: An app
required:
  - name
properties:
  name:
    type: string
    description: Name of the app
    example: weather
  active:
    type: boolean
    description: Is the app active or inactive
    nullable: true
  registered:
    type: boolean
    description: Is the app already registered or not
    nullable: true
