type: object
example: null
nullable: true
properties:
  mode:
    type: string
    enum:
      - avg
      - sum
      - cusum
    description: Pipeline calculation mode
  raster:
    type: array
    items:
      type: string
      enum:
        - S1
        - S2
        - S3
        - S4
        - S5
        - S6
        - S10
        - S12
        - S15
        - S20
        - S30
        - M1
        - M2
        - M3
        - M4
        - M5
        - M6
        - M10
        - M12
        - M15
        - M20
        - M30
        - H1
        - H2
        - H3
        - H4
        - H6
        - H8
        - H12
        - DAY
        - WEEK
        - MONTH
        - QUARTER
        - YEAR
        - DECADE
        - CENTURY
    description: Pipeline calculation intervals