type: object
example: null
nullable: true
properties:
  mode:
    type: string
    enum:
      - avg
      - sum
      - cusum
    nullable: true
    description: Pipeline calculation mode
  raster:
    type: array
    items:
      $ref: 'PipelineRaster.yaml'
